### ISSUE TITLE
How to make a relase jar

### ISSUE THREAD

**Issue by luckcolors** [ata4/disunity#109]
Hello 
i've succefully compiled https://github.com/ata4/disunity
with the command: mvn packageand i got in the 4 folders of the project the compiled jars but no one if them is runnable.
How do i make the relase jar?

**Comment by ata4** [comment]
I don't have a build script for that yet. The fat jar "disunity-dist-0.4.0-SNAPSHOT.jar" contains everything that is required. The GUI, for example, can be started with `java -cp disunity-dist-0.4.0-SNAPSHOT.jar info.ata4.disunity.gui.DisUnityGui`. I guess I'll update the old launcher scripts to run these commands.

**Comment by luckcolors** [comment]
ok thanks :)

**Comment by mersadk** [comment]
How to run a command line interface?
I tried with `java -cp disunity-dist-0.4.0-SNAPSHOT.jar info.ata4.disunity.cli.DisUnityCli` but I get following error:
```
Error: Could not find or load main class info.ata4.disunity.cli.DisUnityCli
```

**Comment by yuyangame** [comment]
I met the same problem with @mersadk 

```shell
$ cd ~/Github/disunity
$ mvn package
$ java -cp disunity-dist-0.4.0-SNAPSHOT.jar info.ata4.disunity.gui.DisUnityGui

Error: Could not find or load main class info.ata4.disunity.cli.DisUnityCli
```

```shell
$ java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
$ mvn -v
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T00:41:47+08:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_66, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.2", arch: "x86_64", family: "mac"
```
