### ISSUE TITLE
Expected a command, got extract

### ISSUE THREAD

**Issue by W-MS** [ata4/disunity#169]
$java -jar disunity.jar extract /Users/wms/Desktop/Data/*.assets
[warning] DisUnityCli: Parameter error: Expected a command, got extract

Disunity v0.5
OS X 10.11.2 (sandbox off)

**Comment by W-MS** [comment]
Thanks a lot!

**Comment by W-MS** [comment]
oh sorry, now i

**Comment by W-MS** [comment]
it's my fault..

**Comment by zahadam** [comment]
PLEASE...you must elaborate on how you fixed your issue...I cant see to get the extract command to work

**Comment by yungdbo** [comment]
Yes please explain how you got an answer to this?

**Comment by patrickgill** [comment]
this is the worst kind of report. oh i fixed it... nm.. i won't tell you how....

**Comment by Mish088** [comment]
Any info about this ? I get the same problem and can't find anything on it.

**Comment by noodog** [comment]
the command is now "disunity bundle unpack resources.assets"
