### ISSUE TITLE
unity 5.3.5 asset bundle - Invalid signature

### ISSUE THREAD

**Issue by liszto** [ata4/disunity#195]
Hi, I try to use disunity 0.5.0 on my asset bundles build with unity 5.3.5 but I get invalid signature error.

Any idea on this ?

**Comment by RupW** [comment]
This is #172: 5.3 now produces UnityFS asset bundles it seems.

**Comment by Mactastic1-5** [comment]
Please close!

**Comment by liszto** [comment]
I'll close !
