### ISSUE TITLE
repeatedly getting Java.lang.outofmemoryerror

### ISSUE THREAD

**Issue by hazesiah** [ata4/disunity#221]
I recently attempted to use disunity to get files from the resources.assets file of the game deemo. I keep getting the error however Java.lang.outofmemoryerror. I've upped the amount of memory allocated to disunity several times to the point where I'm using 12 out of the 16 gigs of ram on my computer but still the error persists. This size of the file is about 1.6 GB, is that way too big for disunity to handle or something? Any answers are appreciated thanks. 
Or, if someone else would like to do the extracting for me, that would be appreciated too.
[Here](https://mega.nz/#!lbwwhBqI!rNsnWMjkVIPmfMbiSOMMjycu9pavwhb3rFmAuF6uox8) it is.

**Comment by Mactastic1-5** [comment]
Use Unity Studio

**Comment by hazesiah** [comment]
That worked perfectly! Thanks a ton!
